### ISSUE TITLE
Invalid object name, \uFFFE

### ISSUE THREAD

**Issue by LordMike** [Genbox/SimpleS3#5]
While testing random characters, I found one that the S3 API does not like, at all.

Code:
```csharp
S3Client client = new S3Client("key-id", "key", AwsRegion.EuWest1));

await client.PutObjectAsync(bucket, "\uFFFE", Stream.Null);
await client.ListObjectsAsync(bucket, r => { r.Prefix = "\uFFFE"; });
```

The exception:
```
There is an error in XML document (2, 101).
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at Genbox.SimpleS3.Core.Internal.Marshal.Response.ListObjectsResponseMarshal.MarshalResponse(ListObjectsRequest request, ListObjectsResponse response, IDictionary`2 headers, Stream responseStream)
   at Genbox.SimpleS3.Core.Requests.MarshalFactory.MarshalResponse[TRequest,TResponse](TRequest request, TResponse response, IDictionary`2 headers, Stream responseStream)
   at Genbox.SimpleS3.Core.Requests.DefaultRequestHandler.<SendRequestAsync>d__8`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp23.Program.<Main>d__2.MoveNext() in C:\Users\MichaelBisbjerg\source\repos\ConsoleApp23\ConsoleApp23\Program.cs:line 489

--- Inner exception
'￾', hexadecimal value 0xFFFE, is an invalid character. Line 2, position 101.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.SetupReadElementContentAsXxx(String methodName)
   at System.Xml.XmlReader.ReadElementContentAsString()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderListBucketResult.Read5_ListBucketResult(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderListBucketResult.Read6_ListBucketResult()
```

Note: This is likely an AWS issue. The Console does not like this either.
![image](https://user-images.githubusercontent.com/1027111/67251123-41db9400-f46e-11e9-9f22-11d7f38aebe3.png)

**Comment by Genbox** [comment]
This is expected as the XML parser in C# does not support non-printable characters. There is a parameter called EncodingType which you can set to Url, and then S3 will URL encode responses. To ensure consistency, I will implement a validation check for places where you can specify a key name + a way to turn it off if needed.

**Comment by LordMike** [comment]
I can see that `\uFFFE` is a "noncharacter" and [should never be used in xml](https://www.w3.org/TR/unicode-xml/#Noncharacters).. 

So it's entirely AWS' fault for allowing this in the first place.

**Comment by Genbox** [comment]
I'm not entirely sure how to handle those characters. I see that some libraries automatically encode anything outside of the printable character range while others stop execution and give an error. Since S3 is an object store, I don't think it is the job of the API client to mess with the name as the behavior can break third-party integrations.

I have added additional validation according to the [AWS S3 docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html), but if the user decides to turn it off (possible with S3Config.ObjectKeyValidationLevel = Level.Level0) then the user also must handle these cases themselves.
